steps:
- script: npm install && npm test
  displayName: Run tests
  continueOnError: true

- script: |
    mkdir ~/.npm-global
    export NPM_CONFIG_PREFIX=~/.npm-global
    export PATH=~/.npm-global/bin:$PATH
    npm install -g vsce
    vsce package
  displayName: Create VSIX

- task: CopyFiles@2
  displayName: Stage VSIX for publishing
  inputs:
    contents: '*.vsix' 
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: Publish VSIX
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: VSIX