steps:
- script: npm test
  displayName: Run tests
  continueOnError: true

- script: |
    mkdir ~/.npm-global
    export NPM_CONFIG_PREFIX=~/.npm-global
    npm install -g vsce
    vsce package
  displayName: Create VSIX

- task: PublishBuildArtifacts@1
  displayName: Publish VSIX
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/*.vsix
    artifactName: VSIX