steps:
- script: npm test
  displayName: Run tests
  continueOnError: true

- script: npm install --global-style vsce
  displayName: Install vsce

- script: vsce package
  displayName: Create VSIX

- task: PublishBuildArtifacts@1
  displayName: Publish VSIX
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/*.vsix
    artifactName: VSIX