stages:
- stage: stage1
  jobs:
  - job: job1
    steps:
    - script: echo hello from entry file 1
- template: my-stages.yml
- stage: stage2
  jobs:
  - job: job2
    steps:
    - script: echo hello from entry file 2